# Generated by Django 4.2.5 on 2023-09-28 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='package_recommendations',
        ),
    ]
